version: '3'
services:
  api:
    build: .
    volumes:
      - .:/src
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*